### ISSUE TITLE
Onix overwrites temperature method settings

### ISSUE THREAD

**Issue by jung-benjamin** [Nuclear-Verification-and-Disarmament/ONIX#2]
Onix always sets the temperature settings method to 'neares'.

In general, most user specified settings for openmc are ignored by the `_read_user_settings` method.
I guess there are some options that should not be used in a coupled transport-depletion mode and therefore it makes sense to 
not allow all user settings options.

However, I think the temperature settings should be changeable by the user. 
This would enable using windowed multipole libraries as well.

**Comment by Rademacher** [comment]
Merged #9, I am considering this issue closed.
