### ISSUE TITLE
ONIX does not check if new material ID is already in use when adding zero dens nuclides to material

### ISSUE THREAD

**Issue by Rademacher** [Nuclear-Verification-and-Disarmament/ONIX#5]
As a part of the _add_zero_dens_nuclides function in the couple module the expanded material is assigned a new material id to separate it from the original material/the same material filling other cells. Unfortunately this reassignment goes by a simple scheme and never checks if the resulting new material ID is already in use. This can lead to a cell being filled with the wrong material. (While OpenMC throws a warning that the material ID is already in use this neither changes this fact, nor does the program stop here - ONIX only crashes way later and with an error that is hard to associate with the actual problem, and it might not even crash in every scenario (I'm not sure), having the mistake possibly go undetected.)

**Comment by Rademacher** [comment]
Turns out there is a global used_ids variable carried by all materials that we could use to check this. The most apparent solution would be to then just increment the id until we arrive at an unused one, though I would propose to instead add in zeroes between the material and cell id, see the example code attached. This would keep up better with the scheme to keep the easy identifiability of initial material and cell. Granted one might mistakenly think the initial material id to have included the zero in the first place, but to me it still seems clearer than adding to the number and losing the direct connection, especially since there usually aren't actually that many (initial) materials but potentially many cells. Since a cell will not be filled by more than one material the 'ID-Ending' given by the cell ID should also not appear again, so this should not overlap with another new material ID. Both of these reasons also make this preferable to adding the zeroes at the end of the ID.
[couple_openmc.txt](https://github.com/Nuclear-Verification-and-Disarmament/ONIX/files/8123746/couple_openmc.txt)
.

**Comment by Rademacher** [comment]
#6

**Comment by jung-benjamin** [comment]
I often receive the Warning: `IDWarning: Another Filter instance already exists with id=3.`
It has not caused any (noticeable) problems for me yet, but may have a similar cause. If yes, then we could fix this at the same time
